### ISSUE TITLE
Something Broke.

### ISSUE THREAD

**Issue by LeaTark** [umbraco/Umbraco.Workflow.Issues#34]
Not sure what log file it wants me to see.

![somethingbroke](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/25925693/e59c43c4-fefe-40d9-9808-6503e720518c)

**Comment by nathanwoulfe** [comment]
Hi @LeaTark, check the logs in the logviewer, there should be more explanation in there. If you could provide reproduction steps that would be useful too.

**Comment by LeaTark** [comment]
OK, found the relevant log

2023-07-26 07:43:13 ERR Unable to generate workflow scaffold: An item with the same key has already been added. Key: 1202
System.ArgumentException: An item with the same key has already been added. Key: 1202
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
at Umbraco.Workflow.Core.Services.Implement.ContentReviewService.SetResponsibleGroups(IEnumerable`1 nodes, ContentReviewsScaffoldModel scaffold)
at Umbraco.Workflow.Core.Services.Implement.ContentReviewService.GetReviewableNodesPage(IList`1 reviewableNodes, InstancesSearchModel searchParams, ContentReviewsSettingsModel settings, ContentReviewsScaffoldModel scaffold)
at Umbraco.Workflow.Core.Services.Implement.ContentReviewService.GetAllForReview[T](InstancesSearchModel searchParams, Nullable`1 offset)
at Umbraco.Workflow.Core.Services.Implement.ContentReviewService.CheckNode(ContentReviewsNodeQueryModel query)
at Umbraco.Workflow.Web.Controllers.ScaffoldController.Get(ScaffoldQueryModel model)

Not sure what I did to cause it but it went away when I removed all individual content reviews.


I found something else in the log that might explain why I haven't received any emails

2023-07-26 04:01:10 ERR Unable to find email template EmbeddedResources/EmailTemplates/ContentReview.cshtml

Though this does appear to be configures on settings > notifications

![image](https://github.com/umbraco/Umbraco.Workflow.Issues/assets/25925693/b1abed03-74d8-4392-991f-1714022821bb)

**Comment by nathanwoulfe** [comment]
Hi @LeaTark are you on Umbraco 10? If so this - https://github.com/umbraco/Umbraco.Workflow.Issues/issues/36#issuecomment-1655092222 - might be useful for email issues.

**Comment by LeaTark** [comment]
I don't know if it's related but there's another bug which has caused some problems for us.
Content templates containing block grid/list create elements with the same keys.
This has caused them to share a common cache, which is overwritten each time any of those pages is published.
Just wondering if that duplicate key might affect Workflow.
https://github.com/umbraco/Umbraco-CMS/issues/13698

**Comment by LeaTark** [comment]
> Hi @LeaTark are you on Umbraco 10? If so this - [#36 (comment)](https://github.com/umbraco/Umbraco.Workflow.Issues/issues/36#issuecomment-1655092222) - might be useful for email issues.

Yes, I am on v10.  Sounds promising.
