### ISSUE TITLE
Selecting a approval group creates an error in the error log

### ISSUE THREAD

**Issue by MikkelBangAtUmbraco** [umbraco/Umbraco.Workflow.Issues#6]
**Versions**: 
Umbraco 10.3.2
Plumber.Workflow: 10.1.1

When creating a new project and installing the plumber/workflow package, everytime you select a approval group you will get an error in the error log.
It wont show anything is wrong with the approval group, no red error boxes, it seems like everything is working in regards to the approval groups

When you then check the error logs it will show an error:
![image](https://user-images.githubusercontent.com/110598923/202435581-bac410b7-dfc0-4c2c-8425-90d1c53ae6b5.png)

**Steps to reproduce:**

1. Install Umbraco locally` - dotnet new umbraco --name MyProject`
2. Run the project locally, do this by opening up the csproj file with Visual Studio.
3. In the installation screen, select a SQL server and input the connection details.
4. Hit OK and it should install the project. 
5. When it's done and you are visited by the backoffice, close the down the project and then install plumber.
6. I used it this way -> manage nuget package -> Search for Plumber.workflow -> Install 10.1.1.
7. Build the project, run the project.
8. log into the backoffice.
9. Approval groups works.

I set it up as a local SQL server db, and connected the project to that.

The issue in itself doesn't seem to have an impact on the approval workflow
creating multiple approval groups.
making some content that will go through the workflow still works.

When selecting any approval group "just" displays the error in the error log.

**Error log**
```
Microsoft.Data.SqlClient.SqlException (0x80131904): The column 'NodeId' was specified multiple times for 'npoco_tbl'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteScalar()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteScalar() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 350
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
ClientConnectionId:3eeb0531-c8a2-4e1e-bbd4-72de1eea37df
Error Number:8156,State:1,Class:16
```
![image](https://user-images.githubusercontent.com/110598923/202436807-a4f88b20-fe45-4ed2-b554-2c50a518045e.png)

**Expected result**
That you can choose the approval group without getting an error in the log

**Actual result**
You get an error message with the bug
![image](https://user-images.githubusercontent.com/110598923/202437223-ba75a85d-79dc-4972-ada0-ff10fa19f4df.png)

**Comment by nathanwoulfe** [comment]
Hey @MikkelBangAtUmbraco, I have a feeling I fixed something related for SQLite, but must have introduced this at the same time... Will deal with it 👍

**Comment by nathanwoulfe** [comment]
Hello again @MikkelBangAtUmbraco 

Pretty sure I've sorted this, will test a bit more then push out a 10.1.2 patch. This was actually breaking UI when viewing a group, then viewing the group's history - was always rendering an empty table, due to the SQL exception.

**Comment by nathanwoulfe** [comment]
Hey @MikkelBangAtUmbraco, this took longer than expected as we decided to release Workflow for Umbraco 10, to replace Plumber, so this fix is part of the latest Workflow release.
